server {
	listen 80;

	location / {
		proxy_pass http://localhost:5173/;
	}

	location /api/ {
		# add to / if you start getting cors errors. should be fine for BE responses
		add_header 'Access-Control-Allow-Origin' '*' always;
		proxy_pass http://localhost:8000/;
	}
}
